apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
namespace: vault-py

resources:
- ../base

configMapGenerator:
- name: vault-py-config
  literals:
  - VAULT_SCHEME=https
  - VAULT_FQDN=vault.v16cp.me
  - K8S_ANNOTATION_PREFIX=vaultpy.io
  - VAULT_AUTH_K8S_PATH=happy_casino_uat
  - VAULT_AUTH_K8S_ROLE=vault-py

patches:
- patch: |-
    - op: add
      path: /spec/template/metadata/labels/env
      value: uat
  target:
    kind: Deployment
    name: vault-py
