---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
  name: vault-py-tls
  namespace: vault-py
spec:
  commonName: vault-py
  isCA: false
  subject:
    organizations:
      - v16
  dnsNames:
    - "vault-py"
    - "vault-py.vault-py.svc"
    - "vault-py.svc.cluster.local"
    - "*.vault-py.vault-py.svc.cluster.local"
    - "localhost"
    - "127.0.0.1"
  issuerRef:
    kind: Issuer
    name: vault-py-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 8760h
  renewBefore: 360h
  secretName: vault-py-tls
