apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
namespace: vault-py
resources:
  - namespace.yaml
  - cluster_issuer.yaml
  - certificate-ca.yaml
  - issuer-ca.yaml
  - certificate.yaml
  - service_account.yaml
  - rbac.yaml
  - admission.yaml
  - deployment.yaml
  - service.yaml
