apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-py-config
  namespace: vault-py
data:
  VAULT_SCHEME: https
  VAULT_FQDN: vault.v16cp.me
  K8S_ANNOTATION_PREFIX: vaultpy.io
  VAULT_AUTH_K8S_PATH: devops-eks
  VAULT_AUTH_K8S_ROLE: vault-py
