apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-py
  namespace: vault-py
spec:
  selector:
    matchLabels:
      app: vault-py
  template:
    metadata:
      labels:
        app: vault-py
    spec:
      serviceAccount: vault-py
      serviceAccountName: vault-py
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
      containers:
        - image: 696813720027.dkr.ecr.ap-east-1.amazonaws.com/vault_py:0.1.0
          imagePullPolicy: IfNotPresent
          name: vault-py
          command: ["uvicorn", "restful:app"]
          envFrom:
            - secretRef:
                name: vault-py-secret
            - configMapRef:
                name: vault-py-config
          resources: {}
