---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-py-cluster-role
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-py
subjects:
  - kind: ServiceAccount
    name: vault-py
    namespace: vault-py
roleRef:
  kind: ClusterRole
  name: vault-py-cluster-role
  apiGroup: rbac.authorization.k8s.io
