---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-py
  namespace: vault-py
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-py-sa
  namespace: vault-py
  annotations:
    kubernetes.io/service-account.name: vault-py
type: kubernetes.io/service-account-token
